# Optional Secrets service (Vault)

version: '3.7'

networks:
  fonoster:

services:

  secrets:
    image: fonoster/vault:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    entrypoint: vault server -config=/vault/config/vault.json   
    # ports:
      # - "127.0.0.1:8200:8200"
    volumes:
      - ${CONFIG}/file:/vault/file:rw
      - ${CONFIG}/vault.json:/vault/config/vault.json:ro
    cap_add:
      - IPC_LOCK
    networks:
      fonoster:

  secrets_api:
    image: fonoster/secrets:${COMPOSE_PROJECT_VERSION}
    environment:
      VAULT_ADDR: ${SECRETS_URL}
      VAULT_TOKEN: ${SECRETS_TOKEN}
      SECRETS_POLICY: ${SECRETS_POLICY}
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secrets_api.entrypoints=internal,websecure"
      - "traefik.http.routers.secrets_api.rule=PathPrefix(`/fonoster.secrets.v1beta1`)"
      - "traefik.http.services.secrets_api.loadbalancer.server.scheme=h2c"
